[workspace]
members = ["libs/hanzo-tools-runner"]
resolver = "2"

[workspace.package]
version = "1.0.2"
repository = "https://github.com/hanzoai/code-runner"
keywords = ["hanzo", "tools", "safe", "ai"]
license-file = "LICENSE"
homepage = "https://hanzo.ai"
readme = "README.md"
edition = "2021"
